[snowflake]
user = "sivanand"
password = "Cvagod@20500000"
account = "https://oknggwt-mb76472.snowflakecomputing.com"
warehouse = "COMPUTE_WH"
database = "PROPERTY_INSPECTION"
schema = "INSPECTION_DATA"