[snowflake]
user = "sivanand"
password = "Cvagod@20500000"
account = "oknggwt-mb76472"
warehouse = "COMPUTE_WH"
database = "PROPERTY_INSPECTION"
schema = "INSPECTION_DATA"

[gemini]
api_key = "AIzaSyCz7zcxQQLwUdXywa6ivYCi9uCZz3nS4g8"